<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon blog!</title>
</head>
<body>
    <header>
        <h1>Bienvenue sur mon blog !</h1>
        <nav>

            <a href="index.php">Accueil</a>
            <a href="index.php?action=contact">Contacts</a>
            <a href="index.php?action=article">Article</a>

        </nav>
    </header>
    
<main>


      <?php include TEMPLATE_DIR . '/'.$template.'.phtml'; ?>


</main>


<footer>
        <nav>
            <a href="index.php?action=mentions">Mentions legales</a>
        </nav>
        <p>Footer</p>

</footer>

</body>
</html>