<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
  
</head>
<body>
	<main>
        <h1>Gestionnaire de tâches :-)</h1>
        <form action="delete.php" method="POST">

<input type="submit" value="Supprimer les tâches" title="Supprimer les tâches sélectionnées">
        <!-- Liste des tâches --> 
<ul>        
<?php foreach ($tasks as $index => $task): ?>
    
        <li><?php echo $task[TITLE] ?>
        <input type="checkbox" id="task-<?=$index?>" name="indexes[]" value="">
        <label for="task-<?=$index?>">
            <?= (strtotime($task[DATE]) < strtotime(date('Y-m-d'))) ? '[ EN RETARD ]' : '';?> 
                   <span class="<?=$task[PRIO];?>"><?=$task[TITLE];?></span>
        </label>
        <a href="delete.php?indexToDelete=<?php echo $index;?>" title="Supprimer cette tâche"><i class="fas fa-trash-alt"></i></a>
        <a href="edit.php?indexToEdit=<?=$index;?>" title="modifier cette tâche"><i class="fas fa-edit"></i></a>
            <p><?php echo $task[DESC] ?></p>
                           
        </li>

    
<?php endforeach?>
</ul>
</form>

        <!-- Formulaire d'ajout --> 
 
        



        <h2>Nouvelle tâche</h2>

<form action="index.php" method="POST">

<fieldset>
<label for="title" id="title" name="title" class="title">Titre</label>
<input type="text" id="title" name="title" value="<?=$title?>">
<?php if (isset($errors['title'])): ?>
                            <p><?=$errors['title'];?></p>
                        <?php endif; ?>
<label for="description" id="description" name="description">Description</label>
<textarea id="description" name="description" placeholder="entrez la decription de votre tâche"></textarea>

<label for="start">Date:</label>
<input type="date" id="date" name="date"
       value="<?php echo date('Y-m-d')?>"
       min="<?php echo date('Y-m-d')?>" max="2025-12-31">

<p>Priorité</p>
  <input type="radio" id="basse" name="priority" value="basse" checked>
  <label for="basse">Basse</label>



  <input type="radio" id="normale" name="priority" value="normale">
  <label for="normale">Normale</label>



  <input type="radio" id="haute" name="priority" value="haute">
  <label for="haute">Haute</label>

 

  <button type="submit" value="Envoyer le formulaire">Enregistrer</button>
</fieldset>
</form>

</main>

    </main>
</body>
</html>